name: Trigger ADO pipeline on push to main

on:
  push:
    branches: [ "main" ]        # fire on every push to main

jobs:
  queue-ado:
    runs-on: ubuntu-latest

    env:
      ADO_PAT: ${{ secrets.ADO_PAT_PIPELINE_SYNC_INVOKER }}        
      ORG: WSSI-AMD
      PROJECT: Carneros
      PIPELINE_ID: 88
      BRANCH: main

    steps:
      - name: Queue Azure DevOps pipeline
        run: |
          # Build request body
          BODY=$(jq -n --arg branch "$BRANCH" '
          {
            resources: {
              repositories: {
                self: {
                  refName: $branch
                }
              }
            }
          }')

          # Debug ‑ print body and URL
          echo "$BODY" | jq
          echo "https://dev.azure.com/$ORG/$PROJECT/_apis/pipelines/$PIPELINE_ID/runs?api-version=7.1"
          

          # Build request body (unchanged) …

          # Create Base-64 value without printing the PAT
          B64_PAT=$(printf ':%s' "$ADO_PAT" | base64 | tr -d '\n')
          
          # Send request
          curl -L -f -sS \
               -H "Content-Type: application/json" \
               -H "Authorization: Basic $B64_PAT" \
               -d "$BODY" \
               "https://dev.azure.com/$ORG/$PROJECT/_apis/pipelines/$PIPELINE_ID/runs?api-version=7.1"

